{{- define "metric_labels.array" -}}
{{ range $key,$value := .metric_labels -}} 
{{ $key }}: "{{ $value }}" 
{{- end }}
{{- end -}}    

{{- define "metric_labels.string" -}}
{{- range $key,$value := .metric_labels -}} {{ $key }}="{{ $value }}", {{- end -}}
{{- end -}}

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Values.destination_service }}-alerts
  namespace: {{ .Release.Namespace }}
  labels:
    prometheus: {{ .Values.prometheus }}
    sre-monitoring: "true"
spec:
  groups:
  - name: SLOs-{{ .Values.destination_service }}
    rules:  
  {{- $params := .Values }}
  {{- $destination_service := $params.destination_service | replace "." "_" }}
  {{- range $alert_key,$alert := .Values.alerts -}}
  {{- range $speed_key,$speed := $alert.speeds -}}
  {{- range $window_key,$window := $speed.windows }}    
      - expr: |
          ( 
            sum(rate(istio_request_duration_seconds_count{connection_security_policy!="none",destination_service="{{ $params.destination_service }}"}[{{ $window }}])) -
            sum(rate(istio_request_duration_seconds_bucket{connection_security_policy!="none",destination_service="{{ $params.destination_service }}",response_code!~"5.*",le="{{ $params.latency }}"}[{{ $window }}]))
          )
          /
          sum(rate(istio_request_duration_seconds_count{connection_security_policy!="none",destination_service="{{ $params.destination_service }}"}[{{ $window }}]))
        labels:
          {{ template "metric_labels.array" $params }}
          service: {{ $params.destination_service }}
        record: virtual_service:{{ $destination_service }}:error_rate_{{ $window }}
  {{- end -}}
  {{- end }}
      - alert: ErrorBudgetBurn
        expr: |
          (
            virtual_service:{{ $destination_service }}:error_rate_{{ $alert.speeds.fast.windows.long }} > ({{ $alert.speeds.fast.burn_rate_percent }}/100*(1-({{ $params.slo_percent }}/100)))
            and
            virtual_service:{{ $destination_service }}:error_rate_{{ $alert.speeds.fast.windows.short }} > ({{ $alert.speeds.fast.burn_rate_percent }}/100*(1-({{ $params.slo_percent }}/100)))
          )
          or
          (
            virtual_service:{{ $destination_service }}:error_rate_{{ $alert.speeds.slow.windows.long }} > ({{ $alert.speeds.slow.burn_rate_percent }}/100*(1-({{ $params.slo_percent }}/100)))
            and
            virtual_service:{{ $destination_service }}:error_rate_{{ $alert.speeds.slow.windows.short }} > ({{ $alert.speeds.slow.burn_rate_percent }}/100*(1-({{ $params.slo_percent }}/100)))
          )
        labels:
          {{ template "metric_labels.array" $params }}
          severity: {{ $alert.severity }}
          service: {{ $params.destination_service }}
  {{- end -}}

          
