
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  client:
    preferService: true
  containers:
  - name: oauth-proxy
    image: openshift/oauth-proxy:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: secret-proxy-tls
        mountPath: /etc/tls/private
      - name: secret-grafana-proxy
        mountPath: /etc/proxy/secrets
    ports:
    - containerPort: 8443
      name: public
    args:
      - '-https-address=:8443'
      - '-provider=openshift'
      - '-openshift-service-account=grafana-serviceaccount'
      - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
      - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}'
      - '-upstream=http://localhost:3001'
      - '-tls-cert=/etc/tls/private/tls.crt'
      - '-tls-key=/etc/tls/private/tls.key'
      - '-client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token'
      - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
      - '-skip-auth-regex=^/metrics'
  secrets:
    - proxy-tls
    - grafana-proxy
  serviceAccount:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-route"}}'
  service:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: proxy-tls
    type: ClusterIP          # Set Service type, either NodePort, ClusterIP or LoadBalancer
    ports:                  # Additional ports to add to the service
      - name: proxy
        port: 443
        protocol: TCP
        targetPort: 8443
    selector:
      app: grafana
  ingress:
    enabled: True
    targetPort: proxy
    termination: reencrypt
  config:
    log:
      mode: "console"
      level: "warn"
    security:
      admin_user: "root"
      admin_password: "secret"
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.basic:
      enabled: False
    auth.anonymous:
      enabled: True
      org_role: Admin
    server:
      http_port: "3001"
      http_addr: 0.0.0.0
  dashboardLabelSelector:
    - matchExpressions:
        - {key: app, operator: In, values: [grafana]}
