apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}  
spec:
  port:
    targetPort: grafana
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: grafana-service