apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: {{ .Values.name }}-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  name: ocp-prometheus.yaml
  datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: "{{ .Values.prometheus_datasource.url }}"
      basicAuth: true
      basicAuthUser: internal
      orgId: 1
      isDefault: true
      version: 1
      basicAuthPassword: "{{ .Values.prometheus_datasource.password }}"
      editable: true
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"
