apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: {{ .Values.name }}-{{ .Values.prometheus_datasource.name }}-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  name: {{ .Values.prometheus_datasource.name }}.yaml
  datasources:
    - name: prometheus-{{ .Values.prometheus_datasource.name }}
      type: prometheus
      access: proxy
      url: "{{ .Values.prometheus_datasource.url }}"
      basicAuth: true
      basicAuthUser: internal
      orgId: 1
      isDefault: {{ .Values.prometheus_datasource.isDefault }}
      version: 1
      secureJsonData:
        basicAuthPassword: "{{ .Values.prometheus_datasource.password }}"
      editable: false
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"
