apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.prometheus.name }}-additional-scrape-configs
  namespace: {{ .Release.Namespace }} 
stringData:
  prometheus-additional.yaml: |
    - job_name: 'federate-platform-prometheus'
      scrape_interval: 30s

      honor_labels: true
      metrics_path: '/federate'

      params:
        'match[]':
          - '{__name__=~".+"}'

      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt

      bearer_token_file: "/var/run/secrets/kubernetes.io/serviceaccount/token"    

      static_configs:
      - targets:
        - 'prometheus-k8s.openshift-monitoring.svc:9091'
        
        labels:
          source: platform

    - job_name: 'federate-istio-prometheus'
      scrape_interval: 30s

      honor_labels: true
      metrics_path: '/federate'

      params:
        'match[]':
          - '{__name__=~".+"}'

      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt

      basic_auth:
        username: internal
        password: {{ .Values.prometheus.istio_endpoint.token }}

      static_configs:
      - targets:
        - 'prometheus.istio-system.svc:9090'
        
        labels:
          source: istio