apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ .Values.prometheus.name }}
  labels:
    prometheus: {{ .Values.prometheus.name }}
  namespace: {{ .Release.Namespace }} 
spec:
  podMetadata:
    labels:
      maistra.io/expose-route: 'true'
  replicas: 2
  serviceAccountName: {{ .Values.prometheus.name }}
  serviceMonitorSelector: {}
  alerting:
    alertmanagers:
    - namespace: {{ .Release.Namespace }}
      name: {{ .Values.alertmanager.name }}
      port: web
  additionalScrapeConfigs:
    name: {{ .Values.prometheus.name }}-additional-scrape-configs
    key: prometheus-additional.yaml
  volumeMounts:
  - name: istio-certs
    mountPath: /etc/istio-certs
  volumes:  
  - name: istio-certs
    secret:
      secretName: istio-certs
      defaultMode: 42
  #serviceAccountName: prometheus
  baseImage: registry.redhat.io/openshift-service-mesh/prometheus-rhel8
  sha: 70960efc418688d96d6e9b1ee8a35905ce221cb08d9e5aefff9616e44b95cd9f      