kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.prometheus.name }}
  namespace: {{ .Release.Namespace }} 
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.prometheus.name }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---  
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.prometheus.name }}-cmo
  namespace: {{ .Release.Namespace }} 
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.prometheus.name }}
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.prometheus.name }}-istio
  namespace: istio-system 
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.prometheus.name }}
roleRef:
  kind: Role
  name: view
  apiGroup: rbac.authorization.k8s.io  
---  
# kind: ClusterRoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: {{ .Values.prometheus.name }}-view
#   namespace: {{ .Release.Namespace }} 
# subjects:
# - kind: ServiceAccount
#   namespace: {{ .Release.Namespace }}
#   name: {{ .Values.prometheus.name }}
# roleRef:
#   kind: ClusterRole
#   name: view
#   apiGroup: rbac.authorization.k8s.io
# ---
# kind: ClusterRoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: {{ .Values.prometheus.name }}-admin
#   namespace: {{ .Release.Namespace }} 
# subjects:
# - kind: ServiceAccount
#   namespace: {{ .Release.Namespace }}
#   name: {{ .Values.prometheus.name }}
# roleRef:
#   kind: ClusterRole
#   name: cluster-admin
#   apiGroup: rbac.authorization.k8s.io    