apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: {{ .Values.grafana.name }}-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  name: sre-prometheus.yaml
  datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-operated.{{ .Release.Namespace }}.svc:9090
    isDefault: true
    version: 1
    editable: false
    jsonData:
      tlsSkipVerify: true
      timeInterval: "5s"      