---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-k8s
  namespace: {{ .Release.Namespace }}
  labels:
    prometheus: k8s
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: prometheus-k8s-tls
spec:
  ports:
    - name: web
      protocol: TCP
      port: 9091
      targetPort: web
  selector:
    app: prometheus
    prometheus: k8s
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
